### ISSUE TITLE
Import webrtc

### ISSUE THREAD

**Issue by francescogatto** [crow-misia/libwebrtc-ktx#1]
Hi!
Awesome library, but at this moment to import webrtc core library I need to do this: 
` implementation 'org.webrtc:google-webrtc:1.0.32006' //m86
    implementation "io.github.zncmn.webrtc:libwebrtc-ktx:0.2.0"`

How can I import Webrtc M88/89 ?

Thanks

**Comment by crow-misia** [comment]
Hi.

If you use m88 or m89, you can use the binary distributed by jitpack.
````
https://jitpack.io/#crow-misia/libwebrtc-bin
````

I have not included it as a dependency so that other binaries distributed by other developers can also be used.

Thanks.

**Comment by francescogatto** [comment]
Very helpfull!

thanks!
